BOT_TOKEN: <<token>>
MESSENGER_TOKEN: 'EAAF5ZA8L6hnUBAH9CjUB2YExM9WMvi3CitPQOzivVwnC3NEKZB7pxhxHeUrXmEDFMqTBEfJZCkV5MUGV3hyT2vppi3w80YBHzO5oMow7iOAfQxEpunp2w2EVSDn1Sq1e32ItNDdQMZAkzdjxMQSdzzKhcy6nsrj3dBIDUfalJt1XYcc7dppy'
MESSENGER_TEST_TOKEN: 'EAACOjXp5gGsBAIater3DokKwRLOSV8ZBEShLZAuoupU2mtj9ra6FvMj4IDwgyk7He2Xw0tZA0OsiK2xZAxK5M1cinlddmRTIsoZCjZAmFP34MOBBkyJaXsMlzLr0EezZBx0LZCTe4UttG9x3J5YjuhqfFE0d6lXistyaFFSAAeuXMgZDZD'
MESSENGER_VERIFY_TOKEN: 'bonobo'